export default {
  aws : 'amazonwebservices',
  amazonwebservices: false,
  android: false,
  angular: ['angularjs', 'plain'],
  angularjs: false,
  apache: false,
  appcelerator: false,
  apple: false,
  atom: false,
  babel: false,
  backbonejs: false,
  behance: false,
  bitbucket: false,
  bootstrap : false,
  bower: ['bower', 'plain'],
  c: false,
  cplusplus: ['cplusplus', 'plain'],
  cpp: ['cplusplus', 'plain'],
  'c++': ['cplusplus', 'plain'],
  cakephp: false,
  ceylon: false,
  chrome: false,
  clojure: false,
  clojurescript: false,
  codeigniter: ['codeigniter', 'plain'],
  coffeescript: false,
  confluence: false,
  couchdb: false,
  csharp: false,
  'c#': ['csharp', 'original'],
  css : ['css3', 'original', 'wordmark'],
  'css3' : ['css3', 'original', 'wordmark'],
  cucumber: ['cucumber', 'plain'],
  d3js: false,
  debian: false,
  devicon: false,
  django:false,
  docker: ['docker', 'plain'],
  doctrine: false,
  'dot-net': false,
  '.net' : ['dot-net', 'original'],
  drupal: false,
  electron: false,
  elm: false,
  ember: ['ember','original','wordkmark'],
  erlang: false,
  express: false,
  facebook:false,
  firefox: ['firefox', 'plain'],
  foundation: false,
  gatling: ['gatlin', 'plain'],
  gimp: ['gimp', 'plain'],
  git: false,
  github: false,
  gitlab: false,
  go: ['go', 'plain'],
  google: false,
  gradle: ['gradle', 'plain'],
  grunt: ['grun', 'plain'],
  gulp: ['gulp', 'plain'],
  handlebars: false,
  heroku: ['heroku', 'plain'],
  'html5': ['html5','original','wordmark'],
  html: ['html5','original','wordmark'],
  ie10: false,
  illustrator: ['illustrator', 'plain'],
  inkscape: ['inskape', 'plain'],
  intellij: false,
  ionic: false,
  jasmine: false,
  java: false,
  javascript: false,
  jeet: false,
  jetbrains: false,
  jquery: false,
  krakenjs: false,
  laravel: ['laravel', 'plain'],
  less: ['less', 'plain', 'wordmark'],
  linkedin: false,
  linux:false,
  meteor: false,
  mocha: ['mocha', 'plain'],
  mongodb: false,
  moodle: false,
  mysql: ['mysql', 'original', 'wordmark'],
  nginx: false,
  nodejs: false,
  node: 'nodejs',
  nodewebkit: false,
  npm: ['npm', 'original', 'wordmark'],
  oracle: false,
  photoshop: ['photoshop', 'plain'],
  php: ['php', 'plain'],
  phpstorm: false,
  postgresql: false,
  protractor: ['protractor', 'plain'],
  pycharm: false,
  python: false,
  rails: ['rails', 'plain', 'wordmark'],
  react: false,
  redhat: false,
  redis: false,
  redux: false,
  ruby: ['ruby', 'plain'],
  rubymine: false,
  safari: false,
  sass: false,
  scss: 'sass',
  sequelize: false,
  sketch: false,
  slack: false,
  sourcetree: false,
  ssh: ['ssh', 'original', 'wordmark'],
  stylus: false,
  swift: false,
  symfony: false,
  tomcat: false,
  travis: ['travis', 'plain'],
  trello: ['trello', 'plain'],
  twitter: false,
  typescript: false,
  ubuntu: ['ubuntu', 'plain'],
  vagrant: false,
  vim: ['vim', 'plain'],
  visualstudio: ['visualstudio', 'plain'],
  vuejs: false,
  webpack: false,
  webstorm: false,
  windows8: false,
  windows: 'windows8',
  wordpress: ['wordpress', 'plain'],
  yarn: false,
  yii: false,
  yunohost: false,
  zend: ['zend', 'plain']
}
