# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, int ]
  pull_request:
    branches: [ master, int ]
    types

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test on Node ${{matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: action/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: npm ci / install
        run: npm ci
      - name: tests
        run: npm test
        env:
          CI: true

  build-and-deploy:
    name: Compilar en Node ${{ matrix.node_version }} y desplegar sobre AWS S3
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12.x']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Instalar dependencias node
        run: npm install
      - name: Build
        run: npm run build
      - name: Copiar/Desplegar a AWS S3
        run: |
          echo Aquí deberían ir la config y comandos de aws s
